/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app-routes/__root'
import { Route as UserAgreementRouteImport } from './app-routes/user-agreement'
import { Route as PrivacyPolicyRouteImport } from './app-routes/privacy-policy'
import { Route as AuthenticatedRouteRouteImport } from './app-routes/_authenticated/route'
import { Route as authRouteRouteImport } from './app-routes/(auth)/route'
import { Route as IndexRouteImport } from './app-routes/index'
import { Route as SetupIndexRouteImport } from './app-routes/setup/index'
import { Route as PricingIndexRouteImport } from './app-routes/pricing/index'
import { Route as ModelCenterIndexRouteImport } from './app-routes/model-center/index'
import { Route as OauthProviderRouteImport } from './app-routes/oauth/$provider'
import { Route as errors503RouteImport } from './app-routes/(errors)/503'
import { Route as errors500RouteImport } from './app-routes/(errors)/500'
import { Route as errors404RouteImport } from './app-routes/(errors)/404'
import { Route as errors403RouteImport } from './app-routes/(errors)/403'
import { Route as errors401RouteImport } from './app-routes/(errors)/401'
import { Route as authSignUpRouteImport } from './app-routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './app-routes/(auth)/sign-in'
import { Route as authResetRouteImport } from './app-routes/(auth)/reset'
import { Route as authOtpRouteImport } from './app-routes/(auth)/otp'
import { Route as authOauthRouteImport } from './app-routes/(auth)/oauth'
import { Route as authForgotPasswordRouteImport } from './app-routes/(auth)/forgot-password'
import { Route as AuthenticatedSystemSettingsRouteRouteImport } from './app-routes/_authenticated/system-settings/route'
import { Route as PricingModelIdIndexRouteImport } from './app-routes/pricing/$modelId/index'
import { Route as ModelCenterModelIdIndexRouteImport } from './app-routes/model-center/$modelId/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './app-routes/_authenticated/users/index'
import { Route as AuthenticatedSystemSettingsIndexRouteImport } from './app-routes/_authenticated/system-settings/index'
import { Route as AuthenticatedRedemptionCodesIndexRouteImport } from './app-routes/_authenticated/redemption-codes/index'
import { Route as AuthenticatedPlaygroundIndexRouteImport } from './app-routes/_authenticated/playground/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './app-routes/_authenticated/models/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './app-routes/_authenticated/dashboard/index'
import { Route as AuthenticatedConsoleIndexRouteImport } from './app-routes/_authenticated/console/index'
import { Route as AuthenticatedChannelsIndexRouteImport } from './app-routes/_authenticated/channels/index'
import { Route as AuthenticatedModelsSectionRouteImport } from './app-routes/_authenticated/models/$section'
import { Route as AuthenticatedDashboardSectionRouteImport } from './app-routes/_authenticated/dashboard/$section'
import { Route as AuthenticatedChatChatIdRouteImport } from './app-routes/_authenticated/chat/$chatId'
import { Route as authUserResetRouteImport } from './app-routes/(auth)/user/reset'
import { Route as AuthenticatedWorkspaceTasksIndexRouteImport } from './app-routes/_authenticated/workspace/tasks/index'
import { Route as AuthenticatedWorkspaceLogsIndexRouteImport } from './app-routes/_authenticated/workspace/logs/index'
import { Route as AuthenticatedWorkspaceKeysIndexRouteImport } from './app-routes/_authenticated/workspace/keys/index'
import { Route as AuthenticatedWorkspaceDocsIndexRouteImport } from './app-routes/_authenticated/workspace/docs/index'
import { Route as AuthenticatedAccountWalletIndexRouteImport } from './app-routes/_authenticated/account/wallet/index'
import { Route as AuthenticatedAccountProfileIndexRouteImport } from './app-routes/_authenticated/account/profile/index'
import { Route as AuthenticatedWorkspaceTasksSectionRouteImport } from './app-routes/_authenticated/workspace/tasks/$section'
import { Route as AuthenticatedSystemSettingsRequestLimitsSectionRouteImport } from './app-routes/_authenticated/system-settings/request-limits/$section'
import { Route as AuthenticatedSystemSettingsModelsSectionRouteImport } from './app-routes/_authenticated/system-settings/models/$section'
import { Route as AuthenticatedSystemSettingsMaintenanceSectionRouteImport } from './app-routes/_authenticated/system-settings/maintenance/$section'
import { Route as AuthenticatedSystemSettingsIntegrationsSectionRouteImport } from './app-routes/_authenticated/system-settings/integrations/$section'
import { Route as AuthenticatedSystemSettingsGeneralSectionRouteImport } from './app-routes/_authenticated/system-settings/general/$section'
import { Route as AuthenticatedSystemSettingsContentSectionRouteImport } from './app-routes/_authenticated/system-settings/content/$section'
import { Route as AuthenticatedSystemSettingsAuthSectionRouteImport } from './app-routes/_authenticated/system-settings/auth/$section'
import { Route as AuthenticatedWorkspaceDocsCategorySlugRouteImport } from './app-routes/_authenticated/workspace/docs/$category/$slug'

const UserAgreementRoute = UserAgreementRouteImport.update({
  id: '/user-agreement',
  path: '/user-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingIndexRoute = PricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelCenterIndexRoute = ModelCenterIndexRouteImport.update({
  id: '/model-center/',
  path: '/model-center/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthProviderRoute = OauthProviderRouteImport.update({
  id: '/oauth/$provider',
  path: '/oauth/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetRoute = authResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => authRouteRoute,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authOauthRoute = authOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedSystemSettingsRouteRoute =
  AuthenticatedSystemSettingsRouteRouteImport.update({
    id: '/system-settings',
    path: '/system-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PricingModelIdIndexRoute = PricingModelIdIndexRouteImport.update({
  id: '/pricing/$modelId/',
  path: '/pricing/$modelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelCenterModelIdIndexRoute = ModelCenterModelIdIndexRouteImport.update({
  id: '/model-center/$modelId/',
  path: '/model-center/$modelId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemSettingsIndexRoute =
  AuthenticatedSystemSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedRedemptionCodesIndexRoute =
  AuthenticatedRedemptionCodesIndexRouteImport.update({
    id: '/redemption-codes/',
    path: '/redemption-codes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlaygroundIndexRoute =
  AuthenticatedPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsoleIndexRoute =
  AuthenticatedConsoleIndexRouteImport.update({
    id: '/console/',
    path: '/console/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChannelsIndexRoute =
  AuthenticatedChannelsIndexRouteImport.update({
    id: '/channels/',
    path: '/channels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsSectionRoute =
  AuthenticatedModelsSectionRouteImport.update({
    id: '/models/$section',
    path: '/models/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSectionRoute =
  AuthenticatedDashboardSectionRouteImport.update({
    id: '/dashboard/$section',
    path: '/dashboard/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authUserResetRoute = authUserResetRouteImport.update({
  id: '/user/reset',
  path: '/user/reset',
  getParentRoute: () => authRouteRoute,
} as any)
const AuthenticatedWorkspaceTasksIndexRoute =
  AuthenticatedWorkspaceTasksIndexRouteImport.update({
    id: '/workspace/tasks/',
    path: '/workspace/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceLogsIndexRoute =
  AuthenticatedWorkspaceLogsIndexRouteImport.update({
    id: '/workspace/logs/',
    path: '/workspace/logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceKeysIndexRoute =
  AuthenticatedWorkspaceKeysIndexRouteImport.update({
    id: '/workspace/keys/',
    path: '/workspace/keys/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceDocsIndexRoute =
  AuthenticatedWorkspaceDocsIndexRouteImport.update({
    id: '/workspace/docs/',
    path: '/workspace/docs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountWalletIndexRoute =
  AuthenticatedAccountWalletIndexRouteImport.update({
    id: '/account/wallet/',
    path: '/account/wallet/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountProfileIndexRoute =
  AuthenticatedAccountProfileIndexRouteImport.update({
    id: '/account/profile/',
    path: '/account/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceTasksSectionRoute =
  AuthenticatedWorkspaceTasksSectionRouteImport.update({
    id: '/workspace/tasks/$section',
    path: '/workspace/tasks/$section',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSystemSettingsRequestLimitsSectionRoute =
  AuthenticatedSystemSettingsRequestLimitsSectionRouteImport.update({
    id: '/request-limits/$section',
    path: '/request-limits/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsModelsSectionRoute =
  AuthenticatedSystemSettingsModelsSectionRouteImport.update({
    id: '/models/$section',
    path: '/models/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsMaintenanceSectionRoute =
  AuthenticatedSystemSettingsMaintenanceSectionRouteImport.update({
    id: '/maintenance/$section',
    path: '/maintenance/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsIntegrationsSectionRoute =
  AuthenticatedSystemSettingsIntegrationsSectionRouteImport.update({
    id: '/integrations/$section',
    path: '/integrations/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsGeneralSectionRoute =
  AuthenticatedSystemSettingsGeneralSectionRouteImport.update({
    id: '/general/$section',
    path: '/general/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsContentSectionRoute =
  AuthenticatedSystemSettingsContentSectionRouteImport.update({
    id: '/content/$section',
    path: '/content/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedSystemSettingsAuthSectionRoute =
  AuthenticatedSystemSettingsAuthSectionRouteImport.update({
    id: '/auth/$section',
    path: '/auth/$section',
    getParentRoute: () => AuthenticatedSystemSettingsRouteRoute,
  } as any)
const AuthenticatedWorkspaceDocsCategorySlugRoute =
  AuthenticatedWorkspaceDocsCategorySlugRouteImport.update({
    id: '/workspace/docs/$category/$slug',
    path: '/workspace/docs/$category/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/system-settings': typeof AuthenticatedSystemSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/oauth': typeof authOauthRoute
  '/otp': typeof authOtpRoute
  '/reset': typeof authResetRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/oauth/$provider': typeof OauthProviderRoute
  '/model-center/': typeof ModelCenterIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/user/reset': typeof authUserResetRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/models/$section': typeof AuthenticatedModelsSectionRoute
  '/channels/': typeof AuthenticatedChannelsIndexRoute
  '/console/': typeof AuthenticatedConsoleIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/models/': typeof AuthenticatedModelsIndexRoute
  '/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/redemption-codes/': typeof AuthenticatedRedemptionCodesIndexRoute
  '/system-settings/': typeof AuthenticatedSystemSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/model-center/$modelId/': typeof ModelCenterModelIdIndexRoute
  '/pricing/$modelId/': typeof PricingModelIdIndexRoute
  '/system-settings/auth/$section': typeof AuthenticatedSystemSettingsAuthSectionRoute
  '/system-settings/content/$section': typeof AuthenticatedSystemSettingsContentSectionRoute
  '/system-settings/general/$section': typeof AuthenticatedSystemSettingsGeneralSectionRoute
  '/system-settings/integrations/$section': typeof AuthenticatedSystemSettingsIntegrationsSectionRoute
  '/system-settings/maintenance/$section': typeof AuthenticatedSystemSettingsMaintenanceSectionRoute
  '/system-settings/models/$section': typeof AuthenticatedSystemSettingsModelsSectionRoute
  '/system-settings/request-limits/$section': typeof AuthenticatedSystemSettingsRequestLimitsSectionRoute
  '/workspace/tasks/$section': typeof AuthenticatedWorkspaceTasksSectionRoute
  '/account/profile/': typeof AuthenticatedAccountProfileIndexRoute
  '/account/wallet/': typeof AuthenticatedAccountWalletIndexRoute
  '/workspace/docs/': typeof AuthenticatedWorkspaceDocsIndexRoute
  '/workspace/keys/': typeof AuthenticatedWorkspaceKeysIndexRoute
  '/workspace/logs/': typeof AuthenticatedWorkspaceLogsIndexRoute
  '/workspace/tasks/': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/workspace/docs/$category/$slug': typeof AuthenticatedWorkspaceDocsCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/oauth': typeof authOauthRoute
  '/otp': typeof authOtpRoute
  '/reset': typeof authResetRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/oauth/$provider': typeof OauthProviderRoute
  '/model-center': typeof ModelCenterIndexRoute
  '/pricing': typeof PricingIndexRoute
  '/setup': typeof SetupIndexRoute
  '/user/reset': typeof authUserResetRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/models/$section': typeof AuthenticatedModelsSectionRoute
  '/channels': typeof AuthenticatedChannelsIndexRoute
  '/console': typeof AuthenticatedConsoleIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/playground': typeof AuthenticatedPlaygroundIndexRoute
  '/redemption-codes': typeof AuthenticatedRedemptionCodesIndexRoute
  '/system-settings': typeof AuthenticatedSystemSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/model-center/$modelId': typeof ModelCenterModelIdIndexRoute
  '/pricing/$modelId': typeof PricingModelIdIndexRoute
  '/system-settings/auth/$section': typeof AuthenticatedSystemSettingsAuthSectionRoute
  '/system-settings/content/$section': typeof AuthenticatedSystemSettingsContentSectionRoute
  '/system-settings/general/$section': typeof AuthenticatedSystemSettingsGeneralSectionRoute
  '/system-settings/integrations/$section': typeof AuthenticatedSystemSettingsIntegrationsSectionRoute
  '/system-settings/maintenance/$section': typeof AuthenticatedSystemSettingsMaintenanceSectionRoute
  '/system-settings/models/$section': typeof AuthenticatedSystemSettingsModelsSectionRoute
  '/system-settings/request-limits/$section': typeof AuthenticatedSystemSettingsRequestLimitsSectionRoute
  '/workspace/tasks/$section': typeof AuthenticatedWorkspaceTasksSectionRoute
  '/account/profile': typeof AuthenticatedAccountProfileIndexRoute
  '/account/wallet': typeof AuthenticatedAccountWalletIndexRoute
  '/workspace/docs': typeof AuthenticatedWorkspaceDocsIndexRoute
  '/workspace/keys': typeof AuthenticatedWorkspaceKeysIndexRoute
  '/workspace/logs': typeof AuthenticatedWorkspaceLogsIndexRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/workspace/docs/$category/$slug': typeof AuthenticatedWorkspaceDocsCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/user-agreement': typeof UserAgreementRoute
  '/_authenticated/system-settings': typeof AuthenticatedSystemSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/oauth': typeof authOauthRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/reset': typeof authResetRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/oauth/$provider': typeof OauthProviderRoute
  '/model-center/': typeof ModelCenterIndexRoute
  '/pricing/': typeof PricingIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/(auth)/user/reset': typeof authUserResetRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/dashboard/$section': typeof AuthenticatedDashboardSectionRoute
  '/_authenticated/models/$section': typeof AuthenticatedModelsSectionRoute
  '/_authenticated/channels/': typeof AuthenticatedChannelsIndexRoute
  '/_authenticated/console/': typeof AuthenticatedConsoleIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/playground/': typeof AuthenticatedPlaygroundIndexRoute
  '/_authenticated/redemption-codes/': typeof AuthenticatedRedemptionCodesIndexRoute
  '/_authenticated/system-settings/': typeof AuthenticatedSystemSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/model-center/$modelId/': typeof ModelCenterModelIdIndexRoute
  '/pricing/$modelId/': typeof PricingModelIdIndexRoute
  '/_authenticated/system-settings/auth/$section': typeof AuthenticatedSystemSettingsAuthSectionRoute
  '/_authenticated/system-settings/content/$section': typeof AuthenticatedSystemSettingsContentSectionRoute
  '/_authenticated/system-settings/general/$section': typeof AuthenticatedSystemSettingsGeneralSectionRoute
  '/_authenticated/system-settings/integrations/$section': typeof AuthenticatedSystemSettingsIntegrationsSectionRoute
  '/_authenticated/system-settings/maintenance/$section': typeof AuthenticatedSystemSettingsMaintenanceSectionRoute
  '/_authenticated/system-settings/models/$section': typeof AuthenticatedSystemSettingsModelsSectionRoute
  '/_authenticated/system-settings/request-limits/$section': typeof AuthenticatedSystemSettingsRequestLimitsSectionRoute
  '/_authenticated/workspace/tasks/$section': typeof AuthenticatedWorkspaceTasksSectionRoute
  '/_authenticated/account/profile/': typeof AuthenticatedAccountProfileIndexRoute
  '/_authenticated/account/wallet/': typeof AuthenticatedAccountWalletIndexRoute
  '/_authenticated/workspace/docs/': typeof AuthenticatedWorkspaceDocsIndexRoute
  '/_authenticated/workspace/keys/': typeof AuthenticatedWorkspaceKeysIndexRoute
  '/_authenticated/workspace/logs/': typeof AuthenticatedWorkspaceLogsIndexRoute
  '/_authenticated/workspace/tasks/': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/_authenticated/workspace/docs/$category/$slug': typeof AuthenticatedWorkspaceDocsCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/user-agreement'
    | '/system-settings'
    | '/forgot-password'
    | '/oauth'
    | '/otp'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/oauth/$provider'
    | '/model-center/'
    | '/pricing/'
    | '/setup/'
    | '/user/reset'
    | '/chat/$chatId'
    | '/dashboard/$section'
    | '/models/$section'
    | '/channels/'
    | '/console/'
    | '/dashboard/'
    | '/models/'
    | '/playground/'
    | '/redemption-codes/'
    | '/system-settings/'
    | '/users/'
    | '/model-center/$modelId/'
    | '/pricing/$modelId/'
    | '/system-settings/auth/$section'
    | '/system-settings/content/$section'
    | '/system-settings/general/$section'
    | '/system-settings/integrations/$section'
    | '/system-settings/maintenance/$section'
    | '/system-settings/models/$section'
    | '/system-settings/request-limits/$section'
    | '/workspace/tasks/$section'
    | '/account/profile/'
    | '/account/wallet/'
    | '/workspace/docs/'
    | '/workspace/keys/'
    | '/workspace/logs/'
    | '/workspace/tasks/'
    | '/workspace/docs/$category/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/user-agreement'
    | '/forgot-password'
    | '/oauth'
    | '/otp'
    | '/reset'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/oauth/$provider'
    | '/model-center'
    | '/pricing'
    | '/setup'
    | '/user/reset'
    | '/chat/$chatId'
    | '/dashboard/$section'
    | '/models/$section'
    | '/channels'
    | '/console'
    | '/dashboard'
    | '/models'
    | '/playground'
    | '/redemption-codes'
    | '/system-settings'
    | '/users'
    | '/model-center/$modelId'
    | '/pricing/$modelId'
    | '/system-settings/auth/$section'
    | '/system-settings/content/$section'
    | '/system-settings/general/$section'
    | '/system-settings/integrations/$section'
    | '/system-settings/maintenance/$section'
    | '/system-settings/models/$section'
    | '/system-settings/request-limits/$section'
    | '/workspace/tasks/$section'
    | '/account/profile'
    | '/account/wallet'
    | '/workspace/docs'
    | '/workspace/keys'
    | '/workspace/logs'
    | '/workspace/tasks'
    | '/workspace/docs/$category/$slug'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/_authenticated'
    | '/privacy-policy'
    | '/user-agreement'
    | '/_authenticated/system-settings'
    | '/(auth)/forgot-password'
    | '/(auth)/oauth'
    | '/(auth)/otp'
    | '/(auth)/reset'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/oauth/$provider'
    | '/model-center/'
    | '/pricing/'
    | '/setup/'
    | '/(auth)/user/reset'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/dashboard/$section'
    | '/_authenticated/models/$section'
    | '/_authenticated/channels/'
    | '/_authenticated/console/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/models/'
    | '/_authenticated/playground/'
    | '/_authenticated/redemption-codes/'
    | '/_authenticated/system-settings/'
    | '/_authenticated/users/'
    | '/model-center/$modelId/'
    | '/pricing/$modelId/'
    | '/_authenticated/system-settings/auth/$section'
    | '/_authenticated/system-settings/content/$section'
    | '/_authenticated/system-settings/general/$section'
    | '/_authenticated/system-settings/integrations/$section'
    | '/_authenticated/system-settings/maintenance/$section'
    | '/_authenticated/system-settings/models/$section'
    | '/_authenticated/system-settings/request-limits/$section'
    | '/_authenticated/workspace/tasks/$section'
    | '/_authenticated/account/profile/'
    | '/_authenticated/account/wallet/'
    | '/_authenticated/workspace/docs/'
    | '/_authenticated/workspace/keys/'
    | '/_authenticated/workspace/logs/'
    | '/_authenticated/workspace/tasks/'
    | '/_authenticated/workspace/docs/$category/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  UserAgreementRoute: typeof UserAgreementRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  OauthProviderRoute: typeof OauthProviderRoute
  ModelCenterIndexRoute: typeof ModelCenterIndexRoute
  PricingIndexRoute: typeof PricingIndexRoute
  SetupIndexRoute: typeof SetupIndexRoute
  ModelCenterModelIdIndexRoute: typeof ModelCenterModelIdIndexRoute
  PricingModelIdIndexRoute: typeof PricingModelIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-agreement': {
      id: '/user-agreement'
      path: '/user-agreement'
      fullPath: '/user-agreement'
      preLoaderRoute: typeof UserAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/': {
      id: '/pricing/'
      path: '/pricing'
      fullPath: '/pricing/'
      preLoaderRoute: typeof PricingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-center/': {
      id: '/model-center/'
      path: '/model-center'
      fullPath: '/model-center/'
      preLoaderRoute: typeof ModelCenterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/$provider': {
      id: '/oauth/$provider'
      path: '/oauth/$provider'
      fullPath: '/oauth/$provider'
      preLoaderRoute: typeof OauthProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset': {
      id: '/(auth)/reset'
      path: '/reset'
      fullPath: '/reset'
      preLoaderRoute: typeof authResetRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/oauth': {
      id: '/(auth)/oauth'
      path: '/oauth'
      fullPath: '/oauth'
      preLoaderRoute: typeof authOauthRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/system-settings': {
      id: '/_authenticated/system-settings'
      path: '/system-settings'
      fullPath: '/system-settings'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/pricing/$modelId/': {
      id: '/pricing/$modelId/'
      path: '/pricing/$modelId'
      fullPath: '/pricing/$modelId/'
      preLoaderRoute: typeof PricingModelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-center/$modelId/': {
      id: '/model-center/$modelId/'
      path: '/model-center/$modelId'
      fullPath: '/model-center/$modelId/'
      preLoaderRoute: typeof ModelCenterModelIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-settings/': {
      id: '/_authenticated/system-settings/'
      path: '/'
      fullPath: '/system-settings/'
      preLoaderRoute: typeof AuthenticatedSystemSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/redemption-codes/': {
      id: '/_authenticated/redemption-codes/'
      path: '/redemption-codes'
      fullPath: '/redemption-codes/'
      preLoaderRoute: typeof AuthenticatedRedemptionCodesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playground/': {
      id: '/_authenticated/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof AuthenticatedPlaygroundIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models/'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/console/': {
      id: '/_authenticated/console/'
      path: '/console'
      fullPath: '/console/'
      preLoaderRoute: typeof AuthenticatedConsoleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/channels/': {
      id: '/_authenticated/channels/'
      path: '/channels'
      fullPath: '/channels/'
      preLoaderRoute: typeof AuthenticatedChannelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/$section': {
      id: '/_authenticated/models/$section'
      path: '/models/$section'
      fullPath: '/models/$section'
      preLoaderRoute: typeof AuthenticatedModelsSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/$section': {
      id: '/_authenticated/dashboard/$section'
      path: '/dashboard/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof AuthenticatedDashboardSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/user/reset': {
      id: '/(auth)/user/reset'
      path: '/user/reset'
      fullPath: '/user/reset'
      preLoaderRoute: typeof authUserResetRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/_authenticated/workspace/tasks/': {
      id: '/_authenticated/workspace/tasks/'
      path: '/workspace/tasks'
      fullPath: '/workspace/tasks/'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/logs/': {
      id: '/_authenticated/workspace/logs/'
      path: '/workspace/logs'
      fullPath: '/workspace/logs/'
      preLoaderRoute: typeof AuthenticatedWorkspaceLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/keys/': {
      id: '/_authenticated/workspace/keys/'
      path: '/workspace/keys'
      fullPath: '/workspace/keys/'
      preLoaderRoute: typeof AuthenticatedWorkspaceKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/docs/': {
      id: '/_authenticated/workspace/docs/'
      path: '/workspace/docs'
      fullPath: '/workspace/docs/'
      preLoaderRoute: typeof AuthenticatedWorkspaceDocsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/wallet/': {
      id: '/_authenticated/account/wallet/'
      path: '/account/wallet'
      fullPath: '/account/wallet/'
      preLoaderRoute: typeof AuthenticatedAccountWalletIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/profile/': {
      id: '/_authenticated/account/profile/'
      path: '/account/profile'
      fullPath: '/account/profile/'
      preLoaderRoute: typeof AuthenticatedAccountProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/tasks/$section': {
      id: '/_authenticated/workspace/tasks/$section'
      path: '/workspace/tasks/$section'
      fullPath: '/workspace/tasks/$section'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksSectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-settings/request-limits/$section': {
      id: '/_authenticated/system-settings/request-limits/$section'
      path: '/request-limits/$section'
      fullPath: '/system-settings/request-limits/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsRequestLimitsSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/models/$section': {
      id: '/_authenticated/system-settings/models/$section'
      path: '/models/$section'
      fullPath: '/system-settings/models/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsModelsSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/maintenance/$section': {
      id: '/_authenticated/system-settings/maintenance/$section'
      path: '/maintenance/$section'
      fullPath: '/system-settings/maintenance/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsMaintenanceSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/integrations/$section': {
      id: '/_authenticated/system-settings/integrations/$section'
      path: '/integrations/$section'
      fullPath: '/system-settings/integrations/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsIntegrationsSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/general/$section': {
      id: '/_authenticated/system-settings/general/$section'
      path: '/general/$section'
      fullPath: '/system-settings/general/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsGeneralSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/content/$section': {
      id: '/_authenticated/system-settings/content/$section'
      path: '/content/$section'
      fullPath: '/system-settings/content/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsContentSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/system-settings/auth/$section': {
      id: '/_authenticated/system-settings/auth/$section'
      path: '/auth/$section'
      fullPath: '/system-settings/auth/$section'
      preLoaderRoute: typeof AuthenticatedSystemSettingsAuthSectionRouteImport
      parentRoute: typeof AuthenticatedSystemSettingsRouteRoute
    }
    '/_authenticated/workspace/docs/$category/$slug': {
      id: '/_authenticated/workspace/docs/$category/$slug'
      path: '/workspace/docs/$category/$slug'
      fullPath: '/workspace/docs/$category/$slug'
      preLoaderRoute: typeof AuthenticatedWorkspaceDocsCategorySlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOauthRoute: typeof authOauthRoute
  authOtpRoute: typeof authOtpRoute
  authResetRoute: typeof authResetRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authUserResetRoute: typeof authUserResetRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOauthRoute: authOauthRoute,
  authOtpRoute: authOtpRoute,
  authResetRoute: authResetRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authUserResetRoute: authUserResetRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface AuthenticatedSystemSettingsRouteRouteChildren {
  AuthenticatedSystemSettingsIndexRoute: typeof AuthenticatedSystemSettingsIndexRoute
  AuthenticatedSystemSettingsAuthSectionRoute: typeof AuthenticatedSystemSettingsAuthSectionRoute
  AuthenticatedSystemSettingsContentSectionRoute: typeof AuthenticatedSystemSettingsContentSectionRoute
  AuthenticatedSystemSettingsGeneralSectionRoute: typeof AuthenticatedSystemSettingsGeneralSectionRoute
  AuthenticatedSystemSettingsIntegrationsSectionRoute: typeof AuthenticatedSystemSettingsIntegrationsSectionRoute
  AuthenticatedSystemSettingsMaintenanceSectionRoute: typeof AuthenticatedSystemSettingsMaintenanceSectionRoute
  AuthenticatedSystemSettingsModelsSectionRoute: typeof AuthenticatedSystemSettingsModelsSectionRoute
  AuthenticatedSystemSettingsRequestLimitsSectionRoute: typeof AuthenticatedSystemSettingsRequestLimitsSectionRoute
}

const AuthenticatedSystemSettingsRouteRouteChildren: AuthenticatedSystemSettingsRouteRouteChildren =
  {
    AuthenticatedSystemSettingsIndexRoute:
      AuthenticatedSystemSettingsIndexRoute,
    AuthenticatedSystemSettingsAuthSectionRoute:
      AuthenticatedSystemSettingsAuthSectionRoute,
    AuthenticatedSystemSettingsContentSectionRoute:
      AuthenticatedSystemSettingsContentSectionRoute,
    AuthenticatedSystemSettingsGeneralSectionRoute:
      AuthenticatedSystemSettingsGeneralSectionRoute,
    AuthenticatedSystemSettingsIntegrationsSectionRoute:
      AuthenticatedSystemSettingsIntegrationsSectionRoute,
    AuthenticatedSystemSettingsMaintenanceSectionRoute:
      AuthenticatedSystemSettingsMaintenanceSectionRoute,
    AuthenticatedSystemSettingsModelsSectionRoute:
      AuthenticatedSystemSettingsModelsSectionRoute,
    AuthenticatedSystemSettingsRequestLimitsSectionRoute:
      AuthenticatedSystemSettingsRequestLimitsSectionRoute,
  }

const AuthenticatedSystemSettingsRouteRouteWithChildren =
  AuthenticatedSystemSettingsRouteRoute._addFileChildren(
    AuthenticatedSystemSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSystemSettingsRouteRoute: typeof AuthenticatedSystemSettingsRouteRouteWithChildren
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedDashboardSectionRoute: typeof AuthenticatedDashboardSectionRoute
  AuthenticatedModelsSectionRoute: typeof AuthenticatedModelsSectionRoute
  AuthenticatedChannelsIndexRoute: typeof AuthenticatedChannelsIndexRoute
  AuthenticatedConsoleIndexRoute: typeof AuthenticatedConsoleIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedPlaygroundIndexRoute: typeof AuthenticatedPlaygroundIndexRoute
  AuthenticatedRedemptionCodesIndexRoute: typeof AuthenticatedRedemptionCodesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkspaceTasksSectionRoute: typeof AuthenticatedWorkspaceTasksSectionRoute
  AuthenticatedAccountProfileIndexRoute: typeof AuthenticatedAccountProfileIndexRoute
  AuthenticatedAccountWalletIndexRoute: typeof AuthenticatedAccountWalletIndexRoute
  AuthenticatedWorkspaceDocsIndexRoute: typeof AuthenticatedWorkspaceDocsIndexRoute
  AuthenticatedWorkspaceKeysIndexRoute: typeof AuthenticatedWorkspaceKeysIndexRoute
  AuthenticatedWorkspaceLogsIndexRoute: typeof AuthenticatedWorkspaceLogsIndexRoute
  AuthenticatedWorkspaceTasksIndexRoute: typeof AuthenticatedWorkspaceTasksIndexRoute
  AuthenticatedWorkspaceDocsCategorySlugRoute: typeof AuthenticatedWorkspaceDocsCategorySlugRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSystemSettingsRouteRoute:
    AuthenticatedSystemSettingsRouteRouteWithChildren,
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedDashboardSectionRoute: AuthenticatedDashboardSectionRoute,
  AuthenticatedModelsSectionRoute: AuthenticatedModelsSectionRoute,
  AuthenticatedChannelsIndexRoute: AuthenticatedChannelsIndexRoute,
  AuthenticatedConsoleIndexRoute: AuthenticatedConsoleIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedPlaygroundIndexRoute: AuthenticatedPlaygroundIndexRoute,
  AuthenticatedRedemptionCodesIndexRoute:
    AuthenticatedRedemptionCodesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkspaceTasksSectionRoute:
    AuthenticatedWorkspaceTasksSectionRoute,
  AuthenticatedAccountProfileIndexRoute: AuthenticatedAccountProfileIndexRoute,
  AuthenticatedAccountWalletIndexRoute: AuthenticatedAccountWalletIndexRoute,
  AuthenticatedWorkspaceDocsIndexRoute: AuthenticatedWorkspaceDocsIndexRoute,
  AuthenticatedWorkspaceKeysIndexRoute: AuthenticatedWorkspaceKeysIndexRoute,
  AuthenticatedWorkspaceLogsIndexRoute: AuthenticatedWorkspaceLogsIndexRoute,
  AuthenticatedWorkspaceTasksIndexRoute: AuthenticatedWorkspaceTasksIndexRoute,
  AuthenticatedWorkspaceDocsCategorySlugRoute:
    AuthenticatedWorkspaceDocsCategorySlugRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  UserAgreementRoute: UserAgreementRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  OauthProviderRoute: OauthProviderRoute,
  ModelCenterIndexRoute: ModelCenterIndexRoute,
  PricingIndexRoute: PricingIndexRoute,
  SetupIndexRoute: SetupIndexRoute,
  ModelCenterModelIdIndexRoute: ModelCenterModelIdIndexRoute,
  PricingModelIdIndexRoute: PricingModelIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
